language: java

sudo: required

os:
  - linux

jdk:
  - oraclejdk8

branches:
  only:
    - master
    - develop

before_install:
  - wget -O - https://downloads.ceylon-lang.org/apt/ceylon-debian-repo.gpg.key | sudo apt-key add -
  - echo "deb https://downloads.ceylon-lang.org/apt/ unstable main" | sudo tee -a /etc/apt/sources.list
  - cat /etc/apt/sources.list
  - sudo apt-get update -qq

install: sudo apt-get install ceylon-1.3.2

script:
- ceylon compile
- ceylon test test.herd.chain/2.0
