language: java

sudo: required

os:
  - linux

jdk:
  - oraclejdk8

branches:
  only:
    - master
    - develop

before_install:
  - wget -O - https://downloads.ceylon-lang.org/apt/ceylon-debian-repo.gpg.key | sudo apt-key add -
  - echo "deb https://downloads.ceylon-lang.org/apt/ unstable main" | sudo tee -a /etc/apt/sources.list
  - cat /etc/apt/sources.list
  - sudo apt-get update -qq

install: sudo apt-get install ceylon-1.3.2

script:
- ceylon compile
- ceylon test test.herd.chain/2.0-rc1

after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then
    echo "We are in $TRAVIS_BRANCH, so we may publish!";
  fi
- if [ "$TRAVIS_BRANCH" == "develop" ]; then
    echo "We are in $TRAVIS_BRANCH, build the docs!";
    ceylon doc herd.chain;
  fi